services:
  bot:
    container_name: s2txt
    build:
      context: .
      dockerfile: Dockerfile
    image: s2txt:latest
    init: true
    environment:
      - PYTHONUNBUFFERED=0
      - TOKEN=${TOKEN}
      - ALLOWED_USER_ID=${ALLOWED_USER_ID}
